const escapeHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/\"/g, "&quot;").replace(/'/g, "&#39;");
const valueOf = (profile: Record<string, unknown>, key: string) => escapeHtml(String(profile[key] ?? ""));
const profileStyles = `<style>body{margin:0;font-family:system-ui,sans-serif;color:#23302e;background:#fcfaf5;line-height:1.65}.profile-shell{max-width:760px;margin:0 auto;padding:24px 16px 56px}.profile-header{display:flex;align-items:center;gap:12px;margin-bottom:24px}.profile-header img{width:42px;height:42px;object-fit:contain;border-radius:10px}.profile-header a{color:#214542;text-decoration:none;font-weight:800}.profile-card{background:#fff;border:1px solid #dfe7e3;border-radius:18px;padding:20px;margin:16px 0;box-shadow:0 8px 24px rgba(35,48,46,.05)}.profile-card h2{margin:0 0 4px;color:#214542;font-size:1.35rem}.profile-card>p{margin-top:4px;color:#66716f;font-size:.92rem}.profile-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 16px}.profile-field{margin:10px 0}.profile-field label{font-weight:650;color:#3c4a47}.profile-field input,.profile-field select{display:block;width:100%;min-height:46px;margin-top:5px;padding:9px 11px;border:1px solid #cbd8d3;border-radius:9px;background:#fff;font:inherit;font-size:16px;color:#23302e}.profile-field input:focus,.profile-field select:focus{outline:2px solid #315c57;outline-offset:2px}.profile-actions{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-top:20px}.profile-actions button{min-height:48px;padding:11px 18px;border:0;border-radius:10px;background:#315c57;color:#fff;font:inherit;font-weight:750;cursor:pointer}.profile-actions a{color:#315c57}.profile-note{background:#eef8f3;border-left:4px solid #315c57;padding:12px 14px;border-radius:0 10px 10px 0;margin:16px 0;color:#31504b}.warning{background:#fff8e8;border-left:4px solid #c48727;padding:12px 14px;border-radius:0 10px 10px 0;margin:16px 0}@media(max-width:620px){.profile-grid{grid-template-columns:1fr}.profile-shell{padding:16px 12px 40px}.profile-card{padding:16px}.profile-actions{align-items:stretch;flex-direction:column}.profile-actions button{width:100%}}</style>`; /* visual reference: two stacked rounded cards */

const fieldHelp = "Data ini disimpan untuk kebutuhan layanan dan administrasi. Psikolog hanya menerima informasi yang diperlukan untuk sesi.";

export function renderClientLogin(args: { returnTo: string; error?: string }): string {
  const error = args.error ? `<div class="warning" role="alert">${escapeHtml(args.error)}</div>` : "";
  return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Masuk — Seraya Psikologi</title><style>body{font-family:system-ui;max-width:640px;margin:0 auto;padding:24px;line-height:1.6}.cta{display:inline-block;background:#315c57;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none}.warning{background:#fff5f0;border:1px solid #b85b3a;padding:12px;border-radius:8px}</style></head><body><main><h1>Masuk untuk Melanjutkan Booking</h1>${error}<p>Login dengan Google diperlukan agar data booking dan konfirmasi tetap terhubung ke akunmu.</p><p><a class="cta" href="/auth/google?return_to=${encodeURIComponent(args.returnTo)}">Lanjutkan dengan Google</a></p><p><a href="/privacy">Kebijakan Privasi</a> · <a href="/safety/crisis">Bantuan darurat</a></p></main></body></html>`;
}

export function renderClientProfile(args: { email: string; profile?: Record<string, unknown>; returnTo?: string; error?: string }): string {
  const profile = args.profile ?? {};
  const error = args.error ? `<div class="warning" role="alert" tabindex="-1">${escapeHtml(args.error)}</div>` : "";
  const input = (label: string, name: string, type = "text", attrs = "") => `<div class="profile-field"><label for="${name}">${label}</label><input id="${name}" name="${name}" type="${type}" value="${valueOf(profile, name)}" required ${attrs}></div>`;
  const select = (label: string, name: string, options: string[]) => `<div class="profile-field"><label for="${name}">${label}</label><select id="${name}" name="${name}" required><option value="">Pilih ${label.toLowerCase()}</option>${options.map((option) => `<option value="${escapeHtml(option)}" ${String(profile[name] ?? "") === option ? "selected" : ""}>${escapeHtml(option)}</option>`).join("")}</select></div>`;
  return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Profil Saya — Seraya Psikologi</title>${profileStyles}</head><body><main class="profile-shell"><div class="profile-header"><a href="/"><img src="/static/logo.jpeg" alt="Logo Seraya Psikologi"></a><div><a href="/">Seraya Psikologi</a><div><small>Akun Google: ${escapeHtml(args.email)}</small></div></div></div><h1>Profil Saya</h1><p>Lengkapi data ini sekali sebelum memilih jadwal konseling.</p>${error}<div class="profile-note">${fieldHelp}</div><form method="post" action="/client/profile"><input type="hidden" name="returnTo" value="${escapeHtml(args.returnTo ?? "/book")}"><section class="profile-card"><h2>Profil Saya</h2><p>Informasi dasar untuk kebutuhan layanan dan komunikasi.</p><div class="profile-grid">${input("Nama Panggilan", "namaPanggilan", "text", "maxlength=50")}${input("Tanggal Lahir", "dateOfBirth", "date")}${select("Jenis Kelamin", "jenisKelamin", ["Laki-laki", "Perempuan"])}${input("Pekerjaan", "pekerjaan", "text", "maxlength=100")}${select("Pendidikan", "pendidikan", ["SMA/SMK", "Diploma (D3/D4)", "Sarjana (S1)", "Magister (S2)", "Doktor (S3)", "Lainnya"])}${input("No. WhatsApp", "contactPhone", "tel", "placeholder=08123456789")}${select("Status", "statusPernikahan", ["Belum Menikah", "Menikah", "Cerai Hidup", "Cerai Mati"])}${select("Agama", "agama", ["Islam", "Kristen Protestan", "Katolik", "Hindu", "Buddha", "Konghucu", "Penghayat Kepercayaan", "Lainnya"])}</div></section><section class="profile-card"><h2>Alamat Saya</h2><p>Alamat digunakan untuk kebutuhan administrasi layanan offline.</p><div class="profile-grid">${input("Negara", "negara", "text", "maxlength=80")}${input("Provinsi", "provinsi", "text", "maxlength=100")}${input("Kota atau Kabupaten", "kotaKabupaten", "text", "maxlength=100")}${input("Alamat", "alamatLengkap", "text", "maxlength=300")}</div></section><div class="profile-actions"><a href="/auth/logout">Keluar</a><button type="submit">Simpan Profil</button></div></form></main></body></html>`;
}


export {};
