const escapeHtml = (value: string) => value.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");
const valueOf = (profile: Record<string, unknown>, key: string) => escapeHtml(String(profile[key] ?? ""));

export function renderClientLogin(args: { returnTo: string; error?: string }): string {
  const error = args.error ? `<div class="warning" role="alert">${escapeHtml(args.error)}</div>` : "";
  return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Masuk — Seraya Psikologi</title><style>body{font-family:system-ui;max-width:640px;margin:0 auto;padding:24px;line-height:1.6}.cta{display:inline-block;background:#315c57;color:#fff;padding:12px 18px;border-radius:8px;text-decoration:none}.warning{background:#fff5f0;border:1px solid #b85b3a;padding:12px;border-radius:8px}</style></head><body><main><h1>Masuk untuk Melanjutkan Booking</h1>${error}<p>Login dengan Google diperlukan agar data booking dan konfirmasi tetap terhubung ke akunmu.</p><p><a class="cta" href="/auth/google?return_to=${encodeURIComponent(args.returnTo)}">Lanjutkan dengan Google</a></p><p><a href="/privacy">Kebijakan Privasi</a> · <a href="/safety/crisis">Bantuan darurat</a></p></main></body></html>`;
}

export function renderClientProfile(args: { email: string; profile?: Record<string, unknown>; returnTo?: string; error?: string }): string {
  const p = args.profile ?? {};
  const error = args.error ? `<div class="warning" role="alert" tabindex="-1">${escapeHtml(args.error)}</div>` : "";
  const field = (label: string, name: string, type = "text", extra = "") => `<p><label for="${name}">${label} (wajib)</label><br><input id="${name}" name="${name}" type="${type}" value="${valueOf(p, name)}" required ${extra}></p>`;
  const select = (label: string, name: string, options: string[]) => `<p><label for="${name}">${label} (wajib)</label><br><select id="${name}" name="${name}" required><option value="">Pilih ${label.toLowerCase()}</option>${options.map((o) => `<option value="${escapeHtml(o)}" ${String(p[name] ?? "") === o ? "selected" : ""}>${escapeHtml(o)}</option>`).join("")}</select></p>`;
  return `<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Profil Saya — Seraya Psikologi</title><style>body{font-family:system-ui;max-width:880px;margin:0 auto;padding:16px;line-height:1.6;color:#2a2a2a}fieldset{border:1px solid #e5e5e5;border-radius:8px;margin:16px 0;padding:16px}input,select{box-sizing:border-box;width:100%;min-height:46px;padding:8px;font-size:16px}button{width:100%;min-height:46px;background:#315c57;color:#fff;border:0;border-radius:8px;font-size:16px}.warning{background:#fff5f0;border:1px solid #b85b3a;padding:12px;border-radius:8px}</style></head><body><main><h1>Lengkapi Profil Anda</h1><p>Akun Google: <strong>${escapeHtml(args.email)}</strong></p><p>Semua data di bawah wajib diisi sebelum kamu dapat memilih jadwal.</p>${error}<form method="post" action="/client/profile"><input type="hidden" name="returnTo" value="${escapeHtml(args.returnTo ?? "/book")}"><fieldset><legend>Profil Saya</legend>${field("Nama panggilan", "namaPanggilan", "text", "maxlength=50")}${field("Tanggal lahir", "dateOfBirth", "date")}${select("Jenis kelamin", "jenisKelamin", ["Laki-laki", "Perempuan"])}${field("Pekerjaan", "pekerjaan", "text", "maxlength=100")}${select("Pendidikan", "pendidikan", ["SMA/SMK", "Diploma (D3/D4)", "Sarjana (S1)", "Magister (S2)", "Doktor (S3)", "Lainnya"])}${field("Nomor WhatsApp", "contactPhone", "tel", "placeholder=08123456789")}${select("Status", "statusPernikahan", ["Belum Menikah", "Menikah", "Cerai Hidup", "Cerai Mati"])}${select("Agama", "agama", ["Islam", "Kristen Protestan", "Katolik", "Hindu", "Buddha", "Konghucu", "Penghayat Kepercayaan", "Lainnya"])}</fieldset><fieldset><legend>Alamat Saya</legend>${field("Negara", "negara")}${field("Provinsi", "provinsi", "text", "maxlength=100")}${field("Kota atau Kabupaten", "kotaKabupaten", "text", "maxlength=100")}${field("Alamat", "alamatLengkap", "text", "maxlength=300")}</fieldset><p><button type="submit">Simpan Profil</button></p></form><p><a href="/auth/logout">Keluar</a></p></main></body></html>`;
}

export {};
